options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ==================================================================
  # == Frontend Service (Vue.js)
  # ==================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend-build'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '.' # Use the Dockerfile in the root directory

  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend-push'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
    waitFor: ['frontend-build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'frontend-deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE_NAME}'
      - '--image=europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--project=${PROJECT_ID}'
    waitFor: ['frontend-push']

  # ==================================================================
  # == Backend Service (Go)
  # ==================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend-build'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
      - './backend' # Specify the backend directory

  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend-push'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
    waitFor: ['backend-build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'backend-deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE_NAME}'
      - '--image=europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--project=${PROJECT_ID}'
      # Set the runtime service account for the new revision. This is critical.
      - '--service-account=${_BACKEND_SA_NAME}'
      # Atomically set all environment variables and secrets for the new revision.
      # This ensures the service starts with the correct configuration.
      # DEBUGGING STEP: Temporarily remove the secret to isolate the problem.
      - '--clear-secrets'
      - '--set-env-vars=CALENDAR_ID=${_CALENDAR_ID},GCAL_AVAILABLE_SLOT_SUMMARY=${_GCAL_AVAILABLE_SLOT_SUMMARY},SMTP_PASS=is-a-dummy-value'
    waitFor: ['backend-push']

# Substitution variables to be configured in the Cloud Build trigger.
substitutions:
  _FRONTEND_SERVICE_NAME: 'ivmanto-com'
  _BACKEND_SERVICE_NAME: 'ivmanto-backend-service'
  _BACKEND_SA_NAME: 'ivmanto-backend-sa'
  _REPO_NAME: 'ivmanto-com-repo'
  _SMTP_SECRET_NAME: 'smtp-password'
  # These must be configured in the Cloud Build Trigger UI.
  _CALENDAR_ID: 'your-calendar-id@group.calendar.google.com'
  _GCAL_AVAILABLE_SLOT_SUMMARY: 'AfB'

# The image created by this build.
images:
  - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
  - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
