options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ==================================================================
  # == Frontend Service (Vue.js)
  # ==================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend-build'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '.' # Use the Dockerfile in the root directory

  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend-push'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
    waitFor: ['frontend-build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'frontend-deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE_NAME}'
      - '--image=europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--project=${PROJECT_ID}'
      - '--allow-unauthenticated'
    waitFor: ['frontend-push']

  # ==================================================================
  # == Backend Service (Go)
  # ==================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend-build'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
      - './backend' # Specify the backend directory

  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend-push'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
    waitFor: ['backend-build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'backend-deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE_NAME}'
      - '--image=europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--project=${PROJECT_ID}'
      - '--allow-unauthenticated'
      # Set the runtime service account for the new revision. This is critical.
      - '--service-account=${_BACKEND_SA_NAME}'
      # The runtime service account needs the "Secret Manager Secret Accessor" role for these secrets.
      - '--set-secrets=SMTP_PASS=${_SMTP_SECRET_NAME}:latest'
      - '--set-secrets=IDEAS_PROMPT=${_IDEAS_PROMPT_SECRET_NAME}:latest'
      # Add the new secret for Google Analytics
      - '--set-secrets=GA_API_SECRET=${_GA_API_SECRET_NAME}:latest'
      # Set environment variables one by one for clarity and to avoid parsing issues with complex strings.
      - '--set-env-vars=CALENDAR_ID=${_CALENDAR_ID}'
      - '--set-env-vars=GCAL_AVAILABLE_SLOT_SUMMARY=${_GCAL_AVAILABLE_SLOT_SUMMARY}'
      - '--set-env-vars=SMTP_HOST=${_SMTP_HOST}'
      - '--set-env-vars=SMTP_PORT=${_SMTP_PORT}'
      - '--set-env-vars=SEND_FROM=${_SEND_FROM}'
      - '--set-env-vars=SEND_FROM_ALIAS=${_SEND_FROM_ALIAS}'
      - '--set-env-vars=GCP_PROJECT_ID=${_GCP_PROJECT_ID}'
      - '--set-env-vars=GCP_LOCATION=${_GCP_LOCATION}'
      # Add the new environment variable for Google Analytics
      - '--set-env-vars=GA_MEASUREMENT_ID=${_GA_MEASUREMENT_ID}'
    waitFor: ['backend-push']

# Substitution variables to be configured in the Cloud Build trigger.
substitutions:
  _FRONTEND_SERVICE_NAME: 'ivmanto-com'
  _BACKEND_SERVICE_NAME: 'ivmanto-backend-service'
  _BACKEND_SA_NAME: 'ivmanto-backend-sa'
  _REPO_NAME: 'ivmanto-com-repo'
  _SMTP_SECRET_NAME: 'smtp-password'
  # These must be configured in the Cloud Build Trigger UI.
  _CALENDAR_ID: 'c_2950137553d97197f3e7963a9543784e119032ca9cc1b970ea668c6e9d2c9764@group.calendar.google.com' # Example, but likely correct
  _GCAL_AVAILABLE_SLOT_SUMMARY: 'AfB' # Example, but likely correct
  _SMTP_HOST: 'smtp.gmail.com' # e.g., 'smtp.gmail.com' - Set in Trigger UI
  _SMTP_PORT: '587' # e.g., '587' - Set in Trigger UI
  _SEND_FROM: 'nikolay.tonev@ivmanto.com' # e.g., 'contact@ivmanto.com' - Set in Trigger UI
  _SEND_FROM_ALIAS: 'IVMANTO Accounts'
  _GCP_PROJECT_ID: 'ivmanto-com-prod'
  _GCP_LOCATION: 'europe-west3'
  _IDEAS_PROMPT_SECRET_NAME: 'ideas-prompt'
  # Add new substitutions for analytics
  _GA_API_SECRET_NAME: 'ga-api-secret' # The name of the secret in Secret Manager
  _GA_MEASUREMENT_ID: 'G-W1TJ3KMZ6V' # Your GA4 Measurement ID - Set in Trigger UI

# The image created by this build.
images:
  - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_FRONTEND_SERVICE_NAME}:${COMMIT_SHA}'
  - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}'
