name: 'email service'
project_id: 'ivm-email-svc'
port: ${PORT}

# email configuration
email_cfg:
  smtp_host: 'smtp.gmail.com'
  smtp_port: '587'
  send_from: 'nikolay.tonev@ivmanto.com'
  send_from_alias: 'accounts@ivmanto.com'
  # The password is taken from .env file
  password: ${SMTP_PASS}
